// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skdibwjttnmdgjrcoaev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrZGlid2p0dG5tZGdqcmNvYWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODIzMTQsImV4cCI6MjA3MjE1ODMxNH0.B4TnH6Cs0__kKQUs2uKF5QlI55qile1XLnf9SkR3gFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});